# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reporter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(648, 608)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.RunButton = QtWidgets.QPushButton(self.centralwidget)
        self.RunButton.setGeometry(QtCore.QRect(260, 170, 111, 31))
        self.RunButton.setObjectName("RunButton")
        self.story_label = QtWidgets.QLabel(self.centralwidget)
        self.story_label.setGeometry(QtCore.QRect(330, 40, 161, 21))
        self.story_label.setObjectName("story_label")
        self.story_input = QtWidgets.QLineEdit(self.centralwidget)
        self.story_input.setGeometry(QtCore.QRect(470, 40, 121, 20))
        self.story_input.setObjectName("story_input")
        self.start_time_label = QtWidgets.QLabel(self.centralwidget)
        self.start_time_label.setGeometry(QtCore.QRect(330, 80, 141, 21))
        self.start_time_label.setObjectName("start_time_label")
        self.end_time_label = QtWidgets.QLabel(self.centralwidget)
        self.end_time_label.setGeometry(QtCore.QRect(330, 120, 141, 21))
        self.end_time_label.setObjectName("end_time_label")
        self.start_time_input = QtWidgets.QLineEdit(self.centralwidget)
        self.start_time_input.setGeometry(QtCore.QRect(470, 80, 121, 20))
        self.start_time_input.setObjectName("start_time_input")
        self.end_time_input = QtWidgets.QLineEdit(self.centralwidget)
        self.end_time_input.setGeometry(QtCore.QRect(470, 120, 121, 20))
        self.end_time_input.setObjectName("end_time_input")
        self.log = QtWidgets.QTextEdit(self.centralwidget)
        self.log.setGeometry(QtCore.QRect(50, 220, 541, 251))
        self.log.setReadOnly(False)
        self.log.setObjectName("log")
        self.psw_label = QtWidgets.QLabel(self.centralwidget)
        self.psw_label.setGeometry(QtCore.QRect(30, 80, 141, 21))
        self.psw_label.setObjectName("psw_label")
        self.psw_input = QtWidgets.QLineEdit(self.centralwidget)
        self.psw_input.setGeometry(QtCore.QRect(120, 80, 181, 20))
        self.psw_input.setObjectName("psw_input")
        self.psw_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.usr_name_label = QtWidgets.QLabel(self.centralwidget)
        self.usr_name_label.setGeometry(QtCore.QRect(30, 40, 161, 21))
        self.usr_name_label.setObjectName("usr_name_label")
        self.usr_name_input = QtWidgets.QLineEdit(self.centralwidget)
        self.usr_name_input.setGeometry(QtCore.QRect(120, 40, 181, 20))
        self.usr_name_input.setObjectName("usr_name_input")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(50, 490, 541, 71))
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "591TestReporter"))
        self.RunButton.setText(_translate("MainWindow", "开始生成"))
        self.story_label.setText(_translate("MainWindow", "请输入需求id："))
        self.start_time_label.setText(_translate("MainWindow", "请输入需求起始日期："))
        self.end_time_label.setText(_translate("MainWindow", "请输入需求结束日期："))
        self.psw_label.setText(_translate("MainWindow", "Tapd 密码："))
        self.usr_name_label.setText(_translate("MainWindow", "Tapd 账户名："))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#676767;\">= 注意 =</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#676767;\">①该脚本未做账密判断，执行前请确保你的账号密码是正确的</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#676767;\">②请正确输入日期格式，例：2022-04-01</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#676767;\">③测试报表地址：https://www.tapd.cn/63835346/report/reports/index</span></p></body></html>"))
